// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NeuroSentryTCNsTcStats struct {
	_                 structs.HostLayout
	TotalPackets      uint64
	IngressPackets    uint64
	EgressPackets     uint64
	SuspiciousPackets uint64
	BytesIn           uint64
	BytesOut          uint64
}

// LoadNeuroSentryTC returns the embedded CollectionSpec for NeuroSentryTC.
func LoadNeuroSentryTC() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NeuroSentryTCBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NeuroSentryTC: %w", err)
	}

	return spec, err
}

// LoadNeuroSentryTCObjects loads NeuroSentryTC and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NeuroSentryTCObjects
//	*NeuroSentryTCPrograms
//	*NeuroSentryTCMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNeuroSentryTCObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNeuroSentryTC()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NeuroSentryTCSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryTCSpecs struct {
	NeuroSentryTCProgramSpecs
	NeuroSentryTCMapSpecs
	NeuroSentryTCVariableSpecs
}

// NeuroSentryTCProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryTCProgramSpecs struct {
	NeurosentryTcEgress  *ebpf.ProgramSpec `ebpf:"neurosentry_tc_egress"`
	NeurosentryTcIngress *ebpf.ProgramSpec `ebpf:"neurosentry_tc_ingress"`
}

// NeuroSentryTCMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryTCMapSpecs struct {
	BlockedIps   *ebpf.MapSpec `ebpf:"blocked_ips"`
	NsTcStatsMap *ebpf.MapSpec `ebpf:"ns_tc_stats_map"`
	TcEvents     *ebpf.MapSpec `ebpf:"tc_events"`
}

// NeuroSentryTCVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryTCVariableSpecs struct {
}

// NeuroSentryTCObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryTCObjects struct {
	NeuroSentryTCPrograms
	NeuroSentryTCMaps
	NeuroSentryTCVariables
}

func (o *NeuroSentryTCObjects) Close() error {
	return _NeuroSentryTCClose(
		&o.NeuroSentryTCPrograms,
		&o.NeuroSentryTCMaps,
	)
}

// NeuroSentryTCMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryTCMaps struct {
	BlockedIps   *ebpf.Map `ebpf:"blocked_ips"`
	NsTcStatsMap *ebpf.Map `ebpf:"ns_tc_stats_map"`
	TcEvents     *ebpf.Map `ebpf:"tc_events"`
}

func (m *NeuroSentryTCMaps) Close() error {
	return _NeuroSentryTCClose(
		m.BlockedIps,
		m.NsTcStatsMap,
		m.TcEvents,
	)
}

// NeuroSentryTCVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryTCVariables struct {
}

// NeuroSentryTCPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryTCPrograms struct {
	NeurosentryTcEgress  *ebpf.Program `ebpf:"neurosentry_tc_egress"`
	NeurosentryTcIngress *ebpf.Program `ebpf:"neurosentry_tc_ingress"`
}

func (p *NeuroSentryTCPrograms) Close() error {
	return _NeuroSentryTCClose(
		p.NeurosentryTcEgress,
		p.NeurosentryTcIngress,
	)
}

func _NeuroSentryTCClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed neurosentrytc_bpfel.o
var _NeuroSentryTCBytes []byte
