// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NeuroSentryLSMConfig struct {
	_            structs.HostLayout
	EnforceMode  uint8
	LogAllAccess uint8
	Padding      [2]uint8
}

type NeuroSentryLSMStats struct {
	_                   structs.HostLayout
	TotalAccessAttempts uint64
	BlockedAccess       uint64
	AllowedAccess       uint64
}

// LoadNeuroSentryLSM returns the embedded CollectionSpec for NeuroSentryLSM.
func LoadNeuroSentryLSM() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NeuroSentryLSMBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NeuroSentryLSM: %w", err)
	}

	return spec, err
}

// LoadNeuroSentryLSMObjects loads NeuroSentryLSM and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NeuroSentryLSMObjects
//	*NeuroSentryLSMPrograms
//	*NeuroSentryLSMMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNeuroSentryLSMObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNeuroSentryLSM()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NeuroSentryLSMSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryLSMSpecs struct {
	NeuroSentryLSMProgramSpecs
	NeuroSentryLSMMapSpecs
	NeuroSentryLSMVariableSpecs
}

// NeuroSentryLSMProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryLSMProgramSpecs struct {
	RestrictModelFileAccess *ebpf.ProgramSpec `ebpf:"restrict_model_file_access"`
}

// NeuroSentryLSMMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryLSMMapSpecs struct {
	ConfigMap           *ebpf.MapSpec `ebpf:"config_map"`
	Events              *ebpf.MapSpec `ebpf:"events"`
	ProtectedExtensions *ebpf.MapSpec `ebpf:"protected_extensions"`
	StatsMap            *ebpf.MapSpec `ebpf:"stats_map"`
	TrustedPids         *ebpf.MapSpec `ebpf:"trusted_pids"`
}

// NeuroSentryLSMVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryLSMVariableSpecs struct {
}

// NeuroSentryLSMObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryLSMObjects struct {
	NeuroSentryLSMPrograms
	NeuroSentryLSMMaps
	NeuroSentryLSMVariables
}

func (o *NeuroSentryLSMObjects) Close() error {
	return _NeuroSentryLSMClose(
		&o.NeuroSentryLSMPrograms,
		&o.NeuroSentryLSMMaps,
	)
}

// NeuroSentryLSMMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryLSMMaps struct {
	ConfigMap           *ebpf.Map `ebpf:"config_map"`
	Events              *ebpf.Map `ebpf:"events"`
	ProtectedExtensions *ebpf.Map `ebpf:"protected_extensions"`
	StatsMap            *ebpf.Map `ebpf:"stats_map"`
	TrustedPids         *ebpf.Map `ebpf:"trusted_pids"`
}

func (m *NeuroSentryLSMMaps) Close() error {
	return _NeuroSentryLSMClose(
		m.ConfigMap,
		m.Events,
		m.ProtectedExtensions,
		m.StatsMap,
		m.TrustedPids,
	)
}

// NeuroSentryLSMVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryLSMVariables struct {
}

// NeuroSentryLSMPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryLSMObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryLSMPrograms struct {
	RestrictModelFileAccess *ebpf.Program `ebpf:"restrict_model_file_access"`
}

func (p *NeuroSentryLSMPrograms) Close() error {
	return _NeuroSentryLSMClose(
		p.RestrictModelFileAccess,
	)
}

func _NeuroSentryLSMClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed neurosentrylsm_bpfel.o
var _NeuroSentryLSMBytes []byte
