// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NeuroSentryXDPConnStats struct {
	_            structs.HostLayout
	EgressBytes  uint64
	IngressBytes uint64
	LastUpdate   uint64
}

type NeuroSentryXDPXdpConfig struct {
	_              structs.HostLayout
	BlockExfil     uint8
	ThresholdBytes uint32
	EnforceMode    uint8
}

type NeuroSentryXDPXdpStats struct {
	_                 structs.HostLayout
	TotalPackets      uint64
	PassedPackets     uint64
	SuspiciousPackets uint64
	ExfilAttempts     uint64
}

// LoadNeuroSentryXDP returns the embedded CollectionSpec for NeuroSentryXDP.
func LoadNeuroSentryXDP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NeuroSentryXDPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NeuroSentryXDP: %w", err)
	}

	return spec, err
}

// LoadNeuroSentryXDPObjects loads NeuroSentryXDP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NeuroSentryXDPObjects
//	*NeuroSentryXDPPrograms
//	*NeuroSentryXDPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNeuroSentryXDPObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNeuroSentryXDP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NeuroSentryXDPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryXDPSpecs struct {
	NeuroSentryXDPProgramSpecs
	NeuroSentryXDPMapSpecs
	NeuroSentryXDPVariableSpecs
}

// NeuroSentryXDPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryXDPProgramSpecs struct {
	NeurosentryXdpFilter *ebpf.ProgramSpec `ebpf:"neurosentry_xdp_filter"`
}

// NeuroSentryXDPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryXDPMapSpecs struct {
	AllowedEgressIps *ebpf.MapSpec `ebpf:"allowed_egress_ips"`
	BlockedIps       *ebpf.MapSpec `ebpf:"blocked_ips"`
	ConnStatsMap     *ebpf.MapSpec `ebpf:"conn_stats_map"`
	NetworkEvents    *ebpf.MapSpec `ebpf:"network_events"`
	TrustedPids      *ebpf.MapSpec `ebpf:"trusted_pids"`
	XdpConfigMap     *ebpf.MapSpec `ebpf:"xdp_config_map"`
	XdpStatsMap      *ebpf.MapSpec `ebpf:"xdp_stats_map"`
}

// NeuroSentryXDPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryXDPVariableSpecs struct {
}

// NeuroSentryXDPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryXDPObjects struct {
	NeuroSentryXDPPrograms
	NeuroSentryXDPMaps
	NeuroSentryXDPVariables
}

func (o *NeuroSentryXDPObjects) Close() error {
	return _NeuroSentryXDPClose(
		&o.NeuroSentryXDPPrograms,
		&o.NeuroSentryXDPMaps,
	)
}

// NeuroSentryXDPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryXDPMaps struct {
	AllowedEgressIps *ebpf.Map `ebpf:"allowed_egress_ips"`
	BlockedIps       *ebpf.Map `ebpf:"blocked_ips"`
	ConnStatsMap     *ebpf.Map `ebpf:"conn_stats_map"`
	NetworkEvents    *ebpf.Map `ebpf:"network_events"`
	TrustedPids      *ebpf.Map `ebpf:"trusted_pids"`
	XdpConfigMap     *ebpf.Map `ebpf:"xdp_config_map"`
	XdpStatsMap      *ebpf.Map `ebpf:"xdp_stats_map"`
}

func (m *NeuroSentryXDPMaps) Close() error {
	return _NeuroSentryXDPClose(
		m.AllowedEgressIps,
		m.BlockedIps,
		m.ConnStatsMap,
		m.NetworkEvents,
		m.TrustedPids,
		m.XdpConfigMap,
		m.XdpStatsMap,
	)
}

// NeuroSentryXDPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryXDPVariables struct {
}

// NeuroSentryXDPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryXDPPrograms struct {
	NeurosentryXdpFilter *ebpf.Program `ebpf:"neurosentry_xdp_filter"`
}

func (p *NeuroSentryXDPPrograms) Close() error {
	return _NeuroSentryXDPClose(
		p.NeurosentryXdpFilter,
	)
}

func _NeuroSentryXDPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed neurosentryxdp_bpfel.o
var _NeuroSentryXDPBytes []byte
