// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NeuroSentryUprobeUprobeStats struct {
	_                structs.HostLayout
	ModelLoadsTotal  uint64
	PickleLoadsTotal uint64
	DangerousPickles uint64
}

// LoadNeuroSentryUprobe returns the embedded CollectionSpec for NeuroSentryUprobe.
func LoadNeuroSentryUprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NeuroSentryUprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NeuroSentryUprobe: %w", err)
	}

	return spec, err
}

// LoadNeuroSentryUprobeObjects loads NeuroSentryUprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NeuroSentryUprobeObjects
//	*NeuroSentryUprobePrograms
//	*NeuroSentryUprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNeuroSentryUprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNeuroSentryUprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NeuroSentryUprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryUprobeSpecs struct {
	NeuroSentryUprobeProgramSpecs
	NeuroSentryUprobeMapSpecs
	NeuroSentryUprobeVariableSpecs
}

// NeuroSentryUprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryUprobeProgramSpecs struct {
	UprobeOnnxLoad     *ebpf.ProgramSpec `ebpf:"uprobe_onnx_load"`
	UprobePickleLoad   *ebpf.ProgramSpec `ebpf:"uprobe_pickle_load"`
	UprobePickleReduce *ebpf.ProgramSpec `ebpf:"uprobe_pickle_reduce"`
	UprobeTfLoad       *ebpf.ProgramSpec `ebpf:"uprobe_tf_load"`
	UprobeTorchLoad    *ebpf.ProgramSpec `ebpf:"uprobe_torch_load"`
	UretprobeTorchLoad *ebpf.ProgramSpec `ebpf:"uretprobe_torch_load"`
}

// NeuroSentryUprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryUprobeMapSpecs struct {
	DangerousSymbols *ebpf.MapSpec `ebpf:"dangerous_symbols"`
	UprobeEvents     *ebpf.MapSpec `ebpf:"uprobe_events"`
	UprobeStatsMap   *ebpf.MapSpec `ebpf:"uprobe_stats_map"`
}

// NeuroSentryUprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NeuroSentryUprobeVariableSpecs struct {
}

// NeuroSentryUprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryUprobeObjects struct {
	NeuroSentryUprobePrograms
	NeuroSentryUprobeMaps
	NeuroSentryUprobeVariables
}

func (o *NeuroSentryUprobeObjects) Close() error {
	return _NeuroSentryUprobeClose(
		&o.NeuroSentryUprobePrograms,
		&o.NeuroSentryUprobeMaps,
	)
}

// NeuroSentryUprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryUprobeMaps struct {
	DangerousSymbols *ebpf.Map `ebpf:"dangerous_symbols"`
	UprobeEvents     *ebpf.Map `ebpf:"uprobe_events"`
	UprobeStatsMap   *ebpf.Map `ebpf:"uprobe_stats_map"`
}

func (m *NeuroSentryUprobeMaps) Close() error {
	return _NeuroSentryUprobeClose(
		m.DangerousSymbols,
		m.UprobeEvents,
		m.UprobeStatsMap,
	)
}

// NeuroSentryUprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryUprobeVariables struct {
}

// NeuroSentryUprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNeuroSentryUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NeuroSentryUprobePrograms struct {
	UprobeOnnxLoad     *ebpf.Program `ebpf:"uprobe_onnx_load"`
	UprobePickleLoad   *ebpf.Program `ebpf:"uprobe_pickle_load"`
	UprobePickleReduce *ebpf.Program `ebpf:"uprobe_pickle_reduce"`
	UprobeTfLoad       *ebpf.Program `ebpf:"uprobe_tf_load"`
	UprobeTorchLoad    *ebpf.Program `ebpf:"uprobe_torch_load"`
	UretprobeTorchLoad *ebpf.Program `ebpf:"uretprobe_torch_load"`
}

func (p *NeuroSentryUprobePrograms) Close() error {
	return _NeuroSentryUprobeClose(
		p.UprobeOnnxLoad,
		p.UprobePickleLoad,
		p.UprobePickleReduce,
		p.UprobeTfLoad,
		p.UprobeTorchLoad,
		p.UretprobeTorchLoad,
	)
}

func _NeuroSentryUprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed neurosentryuprobe_bpfel.o
var _NeuroSentryUprobeBytes []byte
